version: "3"
services:
  colouring-london:
    container_name: colouring-london
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:8080/colouring-london-db
      NODE_ENV: development
      PORT: 8080
      APP_COOKIE_SECRET: 123456
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres-colouring-london
    image: postgres:14
    ports:
      - "5432:5432"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - ./colouring-london/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    restart: always
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: colouring-london-db